### ISSUE TITLE
NoClassDefFoundError attempting to log using 0.3.18

### ISSUE THREAD

**Issue by coreagile** [fzakaria/slf4j-timbre#37]
When upgrading to `0.3.18` of slf4j-timbre, I'm getting the following stack trace:

    java.lang.NoClassDefFoundError: taoensso/timbre$may_log_QMARK_
	    at slf4j_timbre.adapter$_isDebugEnabled.invokeStatic(adapter.clj:159)
        at slf4j_timbre.adapter$_isDebugEnabled.invoke(adapter.clj:158)

These are my relevant dependencies:

    [com.taoensso/timbre "4.10.0"]
    [org.slf4j/log4j-over-slf4j "1.7.30"]
    [org.slf4j/jul-to-slf4j "1.7.30"]
    [org.slf4j/jcl-over-slf4j "1.7.30"]

Verified using `lein deps :tree` that `[com.taoensso/timbre "4.10.0"]` is indeed the version on the classpath.

**Comment by rufoa** [comment]
Sorry about that - will look into it ASAP

Did your code work correctly with 0.3.17?

**Comment by coreagile** [comment]
It sure did! Thanks!

**Comment by rufoa** [comment]
Gotta be a problem with direct linking which the tests miss. Trying to reproduce

**Comment by rufoa** [comment]
The problem is that direct linking isn't playing nicely with the way we use AOT.

We need AOT for our own classes, but this causes our dependencies to undergo AOT as well, so we then strip those classes out of our jar as per [CLJ-322](https://clojure.atlassian.net/browse/CLJ-322) – and this includes Timbre.

If the project using slf4j-timbre (yours) doesn't happen to then AOT Timbre itself, then the invokestatic in our code fails in the way you saw.

I'll look into whether we could overcome this somehow using e.g. `:redef true`, but the immediate fix is to disable direct linking again.

**Comment by rufoa** [comment]
Should be fixed in 0.3.19, please lmk

**Comment by coreagile** [comment]
It works! Thanks!!
